disabled_rules:
- trailing_whitespace
- todo
- vertical_whitespace
opt_in_rules:
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
identifier_name:
  allowed_symbols: "_"
  min_length: 1
  max_length: 50
line_length:
    warning: 250
    error: 275
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 1000
    error: 1500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
large_tuple:
  warning: 5
  error: 6
cyclomatic_complexity:
    warning: 25
    error: 30
reporter: "xcode"
